#!/usr/bin/python3 
# SPDX-FileCopyrightText: 2024 Yuuki Tamada
# SPDX-License-Identifier: BSD-3-Clause

import sys
import random

p = ["🍒", "🍋", "🍊", "🔔", "7", "💎"]

def spin_slot():
    return [random.choice(p) for _ in range(3)]

def result_slot(slot):
    if len(set(slot)) == 1:
        return "ジャックポット!!!!!!" 
    elif len(set(slot)) == 2:
        return "当たり!"
    else:
        return "ハズレ"

def number_of_time():
    try:
        
        spins = int(sys.stdin.read().strip())
        if 1 <= spins <= 10:
            return spins
        else:
            sys.exit(1)  
    except (ValueError, TypeError):
        sys.exit(1)  

def play_slot():
    spins = number_of_time()

    for _ in range(spins):
        slot = spin_slot()
        result = result_slot(slot)
        print(f"{' '.join(slot)} {result}")

if __name__ == "__main__":
    play_slot()
